module.exports = {
  EN: {
    INPUT_ERRORS: 'Input Errors',
    NOT_FOUND: 'Not Found',
    SUCCESS: 'Success',
    FAILURE: 'Failure',
    GET_COMMENT: 'Get Comments',
    SAVE_COMMENT: 'Save Comment',
    COMMENT_SAVE_SUCCESS: 'Comment Save Success',
    COMMENT_SAVE_FAILURE: 'Comment Save Failure',
    COMMENTS_NOT_FOUND: 'Comments Not Found',
    COMMENTS_FETCH_USER_SUCCESS: 'Comments For User Fetch Success',
    COMMENT_LIKE_FAILURE: 'Comment Like/Unlike Failure',
    COMMENT_LIKE_SUCCESS: 'Comment Liked',
    COMMENT_LIKE: 'Comment Like',
    COMMENT_UNLIKE_SUCCESS: 'Comment Unlike Success',
    GET_PROFILE: 'Get Profile',
    SAVE_PROFILE: 'Save Profile',
    PROFILE_SAVE_SUCCESS: 'Profile Save Success',
    PROFILE_SAVE_FAILURE: 'Profile Save Failure',
    PROFILE_NOT_FOUND: 'Profile Not Found',
    PROFILE_FETCH_SUCCESS: 'Profile Fetch Success',
  },
};
